### ISSUE TITLE
Empty file should print a warning.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/hexyl#107]
Another UX issue, but I think an empty (0 byte) file should print a warning or indicator of some sorts (similarly to `bat`). A blank grid might be confusing when someone is under the impression that they're inspecting a non-empty file.

---

Note: I'm doing a class assignment regarding creating tests (from scratch) for an open-source command line program, and I chose hexyl for it. You might have a couple more of these on the way, depending on what the assignment brings to light :)

**Comment by sharkdp** [comment]
Sounds good!
