### ISSUE TITLE
Skipping past the end of a file should print a warning.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/hexyl#108]
Similarly to #107, unknowingly skipping past the end of a file and seeing an empty grid might be confusing for users.

---

Note: I'm doing a class assignment regarding creating tests (from scratch) for an open-source command line program, and I chose hexyl for it. You might have a couple more of these on the way, depending on what the assignment brings to light :)

**Comment by sharkdp** [comment]
Sounds good!
