### ISSUE TITLE
Argument `--block-size=0` should be considered an error.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/hexyl#110]
Using `--length=16block` with `--block-size=0` is the same thing as doing `--length=0`, and it doesn't make much sense to do intentionally.

Related: #106 

---

Note: I'm doing a class assignment regarding creating tests (from scratch) for an open-source command line program, and I chose hexyl for it. You might have a couple more of these on the way, depending on what the assignment brings to light :)

**Comment by sharkdp** [comment]
Thanks. We should disallow block sizes of 0.
