### ISSUE TITLE
Help text doesn't mention the ability to use hex numbers.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/hexyl#113]
Considering hexyl doesn't have a manpage, the `--help` command is the next best thing available to users. A cool feature of hexyl is that sizes and offsets can be specified in hex notation with the `0x` prefix. Unfortunately, nothing in the help text appears to mention it.

---

Note: I'm doing a class assignment regarding creating tests (from scratch) for an open-source command line program, and I chose hexyl for it. You might have a couple more of these on the way, depending on what the assignment brings to light :)

**Comment by ErichDonGubler** [comment]
D'oh. I obviously missed this one. Thanks!
