### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by cup** [sharkdp/hexyl#12]
It looks like Windows did work, but was recently broken

https://github.com/sharkdp/hexyl/commit/57e1c67bfbd146a650148c6d6eea9b1a37896dd4

**Comment by cup** [comment]
https://github.com/sharkdp/hexyl/pull/3

**Comment by sharkdp** [comment]
No, it should still work. I just disabled the Travis build for Windows because it broke the automated deployment. I now know how to fix that, so I can re-enable CI for Windows soon.

**Comment by cup** [comment]
you are fast! I will see if i can try it out later

cheers!
