### ISSUE TITLE
snap no such file error

### ISSUE THREAD

**Issue by delanym** [sharkdp/hexyl#125]
I run

    hexyl outfile

and get "Error: No such file or directory (os error 2)"

I tried removing the snap and reinstalling

hexyl 0.8.0 from Purvesh (badpurvesh11) installed

**Comment by sharkdp** [comment]
FYI @purveshpatel511

**Comment by purveshpatel511** [comment]
@delanym, I am not sure about filetype of `outfile`.
Still you can try following command,
```
hexyl ./outfile
```

And would you please tell me directory tree structure where `outfile` is located and file-type of `outfile`?

**Comment by sharkdp** [comment]
Could this be another "classic confinement" issue? I don't understand how `snap` works, but to be honest, it has cause nothing but problems in the past for me. Not just with your new packages (for which I am really grateful!), but also when I tried to write some myself in the past.

**Comment by purveshpatel511** [comment]
This is not `classic confinement` issue of snap. This is more kind of user local system issue. I also check build logs and not found any error about snap. A `classic confinement` issue would raise `Permission Denied` error. By the way, I am wondering that hexyl also display the binary files??

**Comment by delanym** [comment]
I rebooted and now it works ¯\_(ツ)_/¯

**Comment by sharkdp** [comment]
> By the way, I am wondering that hexyl also display the binary files??

That's kind of.. the purpose of the tool? :D
