### ISSUE TITLE
[Question] Why this specific logo

### ISSUE THREAD

**Issue by j0hnmeow** [sharkdp/hexyl#127]
Why do you have isodurene on the logo? Does it have some special meaning?

**Comment by sharkdp** [comment]
The logo was inspired by the structural formula of Hexanitrodiphenylamine (apparently also known as "hexyl"):

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Hexanitrodiphenylamine.png/799px-Hexanitrodiphenylamine.png)
