### ISSUE TITLE
[Feature] Highlight file signatures

### ISSUE THREAD

**Issue by j0hnmeow** [sharkdp/hexyl#128]
For example, in an ELF file `7F 45 4C 46` could be highlighted in some way (maybe background coloring?)

**Comment by sharkdp** [comment]
Thank you for the request.

That would require us to ship a whole database of file formats / magic numbers, right? I'm afraid this is out of scope for this project.

**Comment by j0hnmeow** [comment]
> That would require us to ship a whole database of file formats / magic numbers, right?

Yeah, but there are existing solutions like libmagic

**Comment by sharkdp** [comment]
Thank you for the request, but I'd rather not add this functionality to `hexyl`. I'd rather keep it simple, for now. Happy to re-open if others voice support for this feature.
