### ISSUE TITLE
Can't Ctrl-C out of editor

### ISSUE THREAD

**Issue by Jamesthe1** [sharkdp/hexyl#132]
When attempting to use Ctrl and C in v0.8.0 (latest), it won't respond to it. I'm not aware of any way to exit the program, and I'm essentially stuck.

**Comment by selfup** [comment]
Not a long term solution but you can:

```
ps aux | grep hexyl
```

Should give you the PID and you can `kill -9 hexyl`

`-9` is `SIGKILL` so it'll be a harsh one but should do the trick.

Sounds like something hung up?

**Comment by sharkdp** [comment]
Thank you for reporting this. I can not reproduce it. Which OS are you on and how exactly are you calling `hexyl`?

**Comment by Jamesthe1** [comment]
This was on Arch Linux, no desktop environment installed at the time.

**Comment by sharkdp** [comment]
@Jamesthe1 Can you reproduce this yourself? With a particular file?

I'm on Arch Linux myself, but I can not reproduce this.

**Comment by Jamesthe1** [comment]
Hi,
This appears to occur when run in `arch-chroot`, now that I remember it.

**Comment by Jamesthe1** [comment]
I have realized the issue. Control-Z is the way out in this mode and it was my own lack of knowledge.
