### ISSUE TITLE
Show help message when using `hexyl` with no argument.

### ISSUE THREAD

**Issue by calio** [sharkdp/hexyl#14]
Just typing `hexyl` without any argument shows just the header of the output. Better to print nothing or help message.

**Comment by sharkdp** [comment]
Thank you for the feedback.

In this case, `hexyl` is waiting for input from stdin. This is intended in order to allow users to pipe output into `hexyl`, i.e.
```
tail -c 1024 some-file | hexyl
```

**Comment by ErichDonGubler** [comment]
It seems like it'd be pretty rare for somebody to be typing in a hex dump by hand. Maybe printing a warning to `stderr` would be appropriate if a TTY is detected?

**Comment by sharkdp** [comment]
> It seems like it'd be pretty rare for somebody to be typing in a hex dump by hand. Maybe printing a warning to `stderr` would be appropriate if a TTY is detected?

That's probably correct and interactive TTY detection on STDIN would be a way to fix this, yes. Are there any other tools that do something like this, i.e. disable input from STDIN if its from a terminal. `hexdump`, `xxd` and all other Unix tools I can think of do not have this behavior.

**Comment by ErichDonGubler** [comment]
@sharkdp: I don't even necessarily know about disabling input if you print a warning, but that's an interesting idea. AFAIK, Unix is the only set of *common* terminal tools that deal with hex dumps. Windows' Powershell has [`Format-Hex`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/format-hex?view=powershell-6), but it's fairly hard to get it to use `stdin` directly anyway.

**Comment by sharkdp** [comment]
I think I'd like to just keep this as is. Maybe someone wants to copy & paste some data into the terminal. For example, copy & paste a Unicode string to see its UTF-8 representation with `hexyl`.

Let me know if somebody has strong opinions on this, so I can reopen the ticket.

**Comment by kilobyte** [comment]
+1 — the old Unix design guideline for command-line tools was/is "no news is good news".
