### ISSUE TITLE
help text is having long lines on wider terminal window

### ISSUE THREAD

**Issue by frogtile** [sharkdp/hexyl#141]
`max_term_width(90)` isn't doing what it should

**Comment by sharkdp** [comment]
Works fine for me. Which platform are you on? What version of `hexyl` do you use and how did you install it?

**Comment by frogtile** [comment]
I am on Fedora 34 and i installed hexyl using dnf

hexyl version: 0.8.0

a7892881f3ee27637a6ff5f7b13290983d280dbd was added after 0.8.0 release

sorry, I should have looked into this before opening the issue
