### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by ardalanForoughipour** [sharkdp/hexyl#146]
I was trying to install this package on Ubuntu at it was raising this error:

```
pkg: error processing archive /var/cache/apt/archives/hexyl_0.6.0-2build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package bat 0.12.1-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/hexyl_0.6.0-2build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

After removing `bat`, the installation was successful. The problem is both software try to create /usr/.crates2.json file. Perhaps writing to /usr/.hexyl/.crates2.json  would be a better option. Same for bat

**Comment by sharkdp** [comment]
Please see https://github.com/sharkdp/bat/issues/938

**Comment by ardalanForoughipour** [comment]
Thank you very much for the response and the wonderful tools you have created.
