### ISSUE TITLE
binary diff

### ISSUE THREAD

**Issue by h-2** [sharkdp/hexyl#150]
Thanks a lot first of all for this really useful tool!

It would be really awesome to be able to view two files side by side with some kind of indicator (red background?) for when they differ! Do you think adding something like that would be possible?

**Comment by sharkdp** [comment]
Thank you for the feedback. It's certainly possible, but I'd rather like to keep hexyl focused on its core functionality. I'm sure there are binary diff programs out there already (?).

You should also be able to do something like
```
diff <(hexyl 1.bin) <(hexyl 2.bin)
```
with some `diff` flags, I guess.
