### ISSUE TITLE
256-color still in use

### ISSUE THREAD

**Issue by remexre** [sharkdp/hexyl#156]
#38 still left some use of 256-colors for gray; when using tmux on the Linux kernel console, this color gets quantitized to black, so addresses are unreadable

https://github.com/sharkdp/hexyl/blob/master/src/lib.rs#L15-L16=

**Comment by sharkdp** [comment]
Thank you for reporting this. What do you suggest we do here? There is no 16 bit gray color, right? Is there any way to detect terminals with no support for 8bit colors?

**Comment by remexre** [comment]
"Light black" is typically treated as gray. I have a patch for this here: https://git.sr.ht/~remexre/hexyl/commit/11488a55b9e5a7c6ba973f142ebc5307b5bb1bae

This seems to work well on my machines; I can PR it if it looks acceptable.

**Comment by sharkdp** [comment]
That doesn't seem to work for me:

![image](https://user-images.githubusercontent.com/4209276/169667180-ae29293c-b59d-4d39-9504-4f7aaecdeda1.png)

**Comment by remexre** [comment]
Hm.... it works on my machine, and [Wikipedia](https://en.wikipedia.org/wiki/Ansi_color#3-bit_and_4-bit) certainly implies it's common but it's of course a color-scheme-dependent thing -- do you know if your color scheme is a common one?

![588fcbc81a2aa50ae785e009139fe22f56b646f7](https://user-images.githubusercontent.com/4196789/169667248-1fa94fa0-fb9b-4d01-a9a8-ec531ed92378.png)

terminfo support could be added to detect terminals that can use 256-color, if we assume that terminals either support 256-color or are using a theme with a "light black" distinct from the background color? Terminfo support _sounds_ like a pain, though I don't know off-hand what's available for it in Rust (so maybe it's not).

Alternatively, theme support would also probably be sufficient, assuming that the themes can specify either 16-color or 256-color colors. (Heck, they probably ought to support truecolor as well.)

I could take a look at implementing either of these sometime next month, I think.

**Comment by sharkdp** [comment]
I'd be fine with adding a `--color-mode=auto/16/8bit` option, where `auto` would currently simply select `8bit` (what we have now) and `16` would be a legacy mode that would not use any 8bit ANSI escape codes.
