### ISSUE TITLE
Feature Request: Show byte 00~1f and 7f in UnixP form in text area

### ISSUE THREAD

**Issue by cheny0y0** [sharkdp/hexyl#163]
That is:
|Byte|Show|
|:---|:---|
|00|^@|
|01|^A|
|02|^B|
|03|^C|
|04|^D|
|05|^E|
|06|^F|
|07|^G|
|08|^H|
|09|^I|
|0a|^J|
|0b|^K|
|0c|^L|
|0d|^M|
|0e|^N|
|0f|^O|
|10|^P|
|11|^Q|
|12|^R|
|13|^S|
|14|^T|
|15|^U|
|16|^V|
|17|^W|
|18|^X|
|19|^Y|
|1a|^Z|
|1b|^[|
|1c|^\|
|1d|^]|
|1e|^^|
|1f|^_|
|7f|^?|

Use the second character to show it in a different color in text area.

**Comment by sharkdp** [comment]
I think this is out of scope for hexyl, unfortunately. It doesn't really fit with its current output width, for example. See also: #6
