### ISSUE TITLE
Hexyl show garbage on LXTerminal

### ISSUE THREAD

**Issue by raspiduino** [sharkdp/hexyl#165]
I'm on Debian 11 on Linux Deploy (a kind of chroot for Android). My phone has an arm64 SoC.

I have installed the arm64 version of Hexyl using `apt`, as you can see in the picture. My LXTerm version is 0.4.0:

![image](https://user-images.githubusercontent.com/68118236/180171361-8e3ed781-49e8-4cc9-93c5-c161ea08c2f6.png)

When I open any binary file using Hexyl, the following things output instead of Hexyl's beautiful interface:

![image](https://user-images.githubusercontent.com/68118236/180170986-c2d5bca1-a259-4172-8aea-f34f35fabb3b.png)

I can still read the hex, but the `?` character is annoying.

What might be the problem? I think LXTerminal support Unicode, doesn't it?

Originally Linux Deploy set the `$LANG` variable to `C`. I tried setting that to `en_US.UTF-8` but got the same result

Any ideas?

Thanks!

**Comment by sharkdp** [comment]
> I think LXTerminal support Unicode, doesn't it?

I don't know. Doesn't look  like it's properly handling the unicode output. Maybe try something like
```
echo "😀"
```

You can try `--border=ascii`, but that will probably still leave the unicode characters in the panel on the right. You can also try to search the issue tracker for "encoding", I think there have been a few other users with similar problems.
