### ISSUE TITLE
Use a different vertical separator character 

### ISSUE THREAD

**Issue by lzybkr** [sharkdp/hexyl#17]
On Windows when I use the Fira Code font in Alacritty, the character `┊` is not available so it looks like this:

![image](https://user-images.githubusercontent.com/2148248/50923118-04d37300-1401-11e9-952d-47c80137fcc8.png)

Fira Code seems like a popular font, so it would be nice to use a different character.

**Comment by sharkdp** [comment]
Hm... I also use Fira Code in my terminal (on Linux) and do not have any problems with that symbol.

**Comment by lzybkr** [comment]
Weird - it does seem to be the font though - this is what I see in the Font Settings control panel (and this also shows I have what seems to be the latest version of the font):

![image](https://user-images.githubusercontent.com/2148248/50924778-64338200-1405-11e9-8087-2948da774e40.png)

**Comment by sharkdp** [comment]
Does this also appear with other fonts?

**Comment by sharkdp** [comment]
Does this also appear with other fonts?

**Comment by roryokane** [comment]
Here are some more data points for the terminal emulators **Terminal** and **iTerm2** on **macOS**. In all of the tested fonts, the character is displayed. In some fonts its alignment is wrong, in others it is correct. The choice of terminal emulator does not make a difference to whether the character is correctly aligned.

I draw no conclusion from this data on whether the character should be changed.

# Fonts in which the character is misaligned

## 16pt Consolas
### Terminal
<img width="842" alt="Terminal 16pt Consolas" src="https://user-images.githubusercontent.com/79168/51422933-c585ee80-1b85-11e9-901d-bf1cdc6c9f66.png">

### iTerm2
<img width="842" alt="iTerm2 16pt Consolas" src="https://user-images.githubusercontent.com/79168/51422936-d33b7400-1b85-11e9-8d5e-ad63548118b4.png">

## 16pt Fira Code
### Terminal
<img width="922" alt="Terminal 16pt Fira Code" src="https://user-images.githubusercontent.com/79168/51422978-8d32e000-1b86-11e9-84aa-07ba9b4005b5.png">

### iTerm2
<img width="922" alt="iTerm2 16pt Fira Code" src="https://user-images.githubusercontent.com/79168/51422980-915efd80-1b86-11e9-87ce-e4db335d44af.png">

## 18pt Ubuntu Mono
### Terminal
<img width="842" alt="Terminal 18pt Ubuntu Mono" src="https://user-images.githubusercontent.com/79168/51422981-94f28480-1b86-11e9-8653-4173800cffeb.png">

### iTerm2
<img width="842" alt="iTerm2 18pt Ubuntu Mono" src="https://user-images.githubusercontent.com/79168/51422982-97ed7500-1b86-11e9-901e-a83f4209ff08.png">


# Fonts in which the character is aligned correctly

## 16pt DejaVu Sans Mono
### Terminal
<img width="922" alt="Terminal 16pt DejaVu Sans Mono" src="https://user-images.githubusercontent.com/79168/51422985-9cb22900-1b86-11e9-8e10-2351c7fc703f.png">

### iTerm2
<img width="922" alt="iTerm2 16pt DejaVu Sans Mono" src="https://user-images.githubusercontent.com/79168/51422988-9f148300-1b86-11e9-8cc0-2d73ae692b40.png">

## 16pt Menlo
### Terminal
<img width="922" alt="Terminal 16pt Menlo" src="https://user-images.githubusercontent.com/79168/51422990-a20f7380-1b86-11e9-986f-a821505c70bd.png">

### iTerm2
<img width="922" alt="iTerm2 16pt Menlo" src="https://user-images.githubusercontent.com/79168/51422994-a5a2fa80-1b86-11e9-84a0-6e33ab7b14e4.png">

**Comment by sharkdp** [comment]
@roryokane Thank you!

If somebody wants to suggest a different character (or maybe just remove the additional vertical lines), I'd be ok with changing this.

**Comment by dmke** [comment]
Maybe a CLI flag to disable `┊`?

Or a `--borders={fancy,simple,none}` flag, where `fancy is the curent default, `simple` either removes `┊` or replaces it with `|`, and `none` disables both horizontal and vertical borders (I personally question the usefulness of the bordering, and would `alias hexyl='command hexyl --borders=none` immediately ;-)).

**Comment by sharkdp** [comment]
What do others think? Should we just remove the borders completely?

**Comment by dmke** [comment]
Here's a mockup quickly cobbled together:

![image](https://user-images.githubusercontent.com/327411/53598241-7b405600-3ba4-11e9-8918-4c1971fe2b5c.png)

Note, this only removed horizontal borders and replaced the vertical ones with a space.

**Comment by sharkdp** [comment]
Closed via #54 by @dmke.
