### ISSUE TITLE
`--no-characters` causes output artifacts when squeezing lines

### ISSUE THREAD

**Issue by ravenexp** [sharkdp/hexyl#171]
Sample output:

```
│000000d0│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │
│*       │                         ┊                         │        ┊        │
│000000f0│ 00 00 c8 43 00 80 54 44 ┊ 00 02 00 02 04 00 00 00 │
```

Note the extra `┊        │` on the right.

**Comment by sharkdp** [comment]
Thank you for reporting this.

FYI @mkatychev only if you are interested, of course.

**Comment by mkatychev** [comment]
Yeah I can take a look when I get some time this coming week.

@ravenexp does this happen with any data in `./tests/examples/`? What's the full command you used and anything else that might help reproduce this.

**Comment by ravenexp** [comment]
> @ravenexp does this happen with any data in `./tests/examples/`? What's the full command you used and anything else that might help reproduce this.

Yes, the simplest way to reproduce is to run:

```
cargo run -- -C tests/examples/hello_world_elf64
```

**Comment by mkatychev** [comment]
@sharkdp  https://github.com/sharkdp/hexyl/pull/174 is out in draft

**Comment by sharkdp** [comment]
I understand this is now closed via https://github.com/sharkdp/hexyl/pull/173 and https://github.com/sharkdp/hexyl/pull/177
