### ISSUE TITLE
Add support for the NO_COLOR environment variable

### ISSUE THREAD

**Issue by mjf** [sharkdp/hexyl#179]
Please, add support for the [`NO_COLOR`](https://no-color.org/) environment variable, if possible.

**Comment by sharkdp** [comment]
Sure, sounds reasonable.

**Comment by mainrs** [comment]
This can be done by using another dependency for colored text instead of the current one.
owo-colors supports the env variable natively and has zero overhead printing colored text.

I can work on this issue if that's ok.

**Comment by nagy** [comment]
Is it possible, that this has not really been fixed? When I run `NO_COLOR=1 hexyl <<< hi` I still see colored output. Am I doing something wrong?  That is on hexyl version `0.13.1`.

**Comment by sharkdp** [comment]
Strange. Doesn't work for me either. Re-opening for now.
