### ISSUE TITLE
Support 16 color terminal output

### ISSUE THREAD

**Issue by tiziano88** [sharkdp/hexyl#18]
this would allow people using colorschemes they may have set up on their terminal emulator. It should be an easy change and I'm happy to make it myself, but let me know if you would agree to such change in the first place, thanks!

**Comment by sharkdp** [comment]
@tiziano88 I have recently fixed #9, but we are still "stuck" with the given color scheme (molokai) which is hard-coded. I'm fine with this, but if you think this should definitely be fixed, I'm open for proposals.

What I would like to avoid is a full-blown way of customizing the output in every possible way. I'd like to keep it simple.

**Comment by tiziano88** [comment]
Thanks @sharkdp ! I think a potentially more viable approach would be to actually use 16 colors rather than 256, since usually terminal emulators are configured with those 16 colors according to a user-defined theme (e.g. solarized). I think that would remove the need for any customisation in hexyl itself. WDYT?

**Comment by sharkdp** [comment]
This could be worth a try, but I'd like to see how the output would look like in various "popular" terminal color schemes.

There will be no way to enforce that different byte groups can be easily visually distinguished. We would probably keep a fixed gray color for the NULL byte but we have to randomly(?) take four of those base colors and hope that they are not too similar in the given color scheme.

Or am I misunderstanding something here?

**Comment by sharkdp** [comment]
closed via #38.

**Comment by sharkdp** [comment]
Fixed in [v0.4.0](https://github.com/sharkdp/hexyl/releases/tag/v0.4.0).
