### ISSUE TITLE
Incorrect output when reading from terminal

### ISSUE THREAD

**Issue by Aaron-Rumpler** [sharkdp/hexyl#196]
Hexyl is giving incorrect output in some cases when reading terminal input. I've seen it when the input has multiple newlines at the end. The input of `Test[Enter][Enter][Enter][Enter][CTRL-D]` is one such case:

```
❯ hexyl
Test



┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 54 65 73 74 0a 0a 00 00 ┊ 00 00 00 00 00 00 00 00 │Test__⋄⋄┊⋄⋄⋄⋄⋄⋄⋄⋄│
│00000010│ 0a 0a 73 74 0a 0a 00 00 ┊ 00 00 00 00 00 00 00 00 │__st__⋄⋄┊⋄⋄⋄⋄⋄⋄⋄⋄│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

I've been able to track it back to 15e8abfc9afe95a221c9c9a265cf3fb58fed0470 through 5f82942f98fc69af8f76701715053aee2451d62c, with it being introduced in that set of changes.

**Comment by Aaron-Rumpler** [comment]
I should probably mention I tested this on macOS 13.4 and tried from both Bash and ZSH in both iTerm2 and Terminal.

**Comment by sharifhsn** [comment]
I can reproduce this issue on Linux. I'll take a look at it today, thanks for raising an issue!
