### ISSUE TITLE
Feature request: Ship as a crate

### ISSUE THREAD

**Issue by dmtrKovalenko** [sharkdp/hexyl#198]
That would be very helpful if you will consider shipping the core lib as rust crate outside of binary, this will allow to integrate hexyl in a lot of different scenarios, one of them my BLE browser project where I want to show binary viewer of the incoming data

**Comment by sharkdp** [comment]
But… it already is: https://docs.rs/hexyl/latest/hexyl/

**Comment by sharkdp** [comment]
we also have an example on how to use it: https://github.com/sharkdp/hexyl/blob/master/examples/simple.rs

**Comment by dmtrKovalenko** [comment]
Wow that is awesome! Thanks an sorry for bothering :)
