### ISSUE TITLE
unreadable output on pwsh 6 on windows 10

### ISSUE THREAD

**Issue by WangZishi** [sharkdp/hexyl#2]
![image](https://user-images.githubusercontent.com/8288105/48261874-6f951c00-e45b-11e8-9c5a-f695ea585beb.png)

**Comment by sharkdp** [comment]
Thank you for reporting this. I haven't tried it on Windows at all. Could you try to build from this branch (https://github.com/sharkdp/hexyl/pull/3) and see if this solves the problem?
