### ISSUE TITLE
Feature Request: Support string input from command line

### ISSUE THREAD

**Issue by cblair** [sharkdp/hexyl#20]
Requesting that hexyl can read string from the command line instead of just files.

**Comment by ErichDonGubler** [comment]
You can use `stdin` right now:

```
$ echo string | hexyl

┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 73 74 72 69 6e 67 0a    ┊                         │string_ ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘

```

...so I think that you can already do this? What was your use case specifically?

**Comment by cblair** [comment]
I think that's good enough, sorry I missed that it read from stdin.
