### ISSUE TITLE
Add option to print the color table

### ISSUE THREAD

**Issue by aplzr** [sharkdp/hexyl#229]
It would be nice to have an option like `--print-color-table` that, well, prints the color table 🙂 It would mean not having to look it up in the [readme](https://github.com/sharkdp/hexyl?tab=readme-ov-file#color-reference) (which also seems to be missing what the color red denotes in the output).

Another benefit would be that it would show the color coding on the current system, which might be different from what's shown in the readme.

**Comment by sharkdp** [comment]
Sounds good.

> seems to be missing what the color red denotes in the output

That should also be fixed.

**Comment by aplzr** [comment]
Thanks @sahinfalcon and @sharkdp 👍
