### ISSUE TITLE
Pattern matching to some format of files, mp3, exe, and so on

### ISSUE THREAD

**Issue by chanmaoganda** [sharkdp/hexyl#230]
# Add some internal `pattern script` to parse bytes in a certain format pattern？
Add some patterns to recognize blocks in the matched pattern.

## Example:
A mp3 file has a id3 tag, id3 tag has some blocks, can we highlight those blocks and highlight the whole tag block?

**Comment by sharifhsn** [comment]
This feature seems quite out of scope for `hexyl`. Beyond that, the current implementation details of `hexyl` would make this infeasible. Files are processed and printed line by line, with the size of the line being arbitrary in length. There's no way for `hexyl` to "look ahead", recognize some structure, and highlight the line it's processing.

The only version of this that would be somewhat feasible would be to allow custom styling of specific bytes that carry some meaning to the user. But anything more than single-byte styling is impossible.
