### ISSUE TITLE
Pale cyan on white background

### ISSUE THREAD

**Issue by vi** [sharkdp/hexyl#34]
![screenshot](https://user-images.githubusercontent.com/173219/51072548-9d712980-1673-11e9-90ca-d7bde24032b9.png)

In gnome-terminal or in xterm or in lxterminal.

Only looks properly in Linux text console (probably because of it has dark background).

**Comment by vi** [comment]
If Hexyl is intended to be used only on dark background, then force black background for all Hexyl output.

**Comment by kilobyte** [comment]
I tried forcing dark background in a program of mine once, and people complained.  Turns out the wrong-thinkers who insist on a white background are adamant in their heresy...

**Comment by sharkdp** [comment]
No, I also think forcing a background color would be a bad decision. It would probably also not look great. I'd say we should probably move forward with #18, which would also solve this (*if* users have a decent base color scheme).

**Comment by vi** [comment]
Maybe hexyl needs overridable/configurable colour schemes (including grayscale)?

**Comment by kilobyte** [comment]
Perhaps; but any extra customization risks becoming bloat.

**Comment by sharkdp** [comment]
closed via #38.

**Comment by sharkdp** [comment]
Fixed in [v0.4.0](https://github.com/sharkdp/hexyl/releases/tag/v0.4.0).
