### ISSUE TITLE
Please use (or support) -c for byte count

### ISSUE THREAD

**Issue by FauxFaux** [sharkdp/hexyl#46]
`hexyl -n 100` is, in my mind, replacing `head -c 100 | xxd`. If it is directly replacing `xxd`, `xxd` calls this option `-l` (`length`, which I had to look up, because I use `head`).

Please support `-c`, with the same behaviour as the current `-n`, and/or improve the error output to remind users of the correct option:

```
% hexyl -c 257 /dev/urandom
error: Found argument '-c' which wasn't expected, or isn't valid in this context

USAGE:
    hexyl [file]

For more information try --help
```

Annoyingly, `xxd` uses `-c` for `cols`.

**Comment by sharkdp** [comment]
I used `-n` for `--length` because that is used in `hexdump`. I'm okay with adding an additional alias `-c`.

**Comment by selfup** [comment]
I made a small PR, but multiple shortnames does not seem to be an option for `clap`.

I made some suggestions, but otherwise `--c` would be the easiest compromise 🙏

**Comment by sharkdp** [comment]
@selfup Thanks for looking into this. That's a pitty. Maybe this is something that should be requested in `clap`.

> I made some suggestions, but otherwise `--c` would be the easiest compromise

I'm not a big fan of adding `--c`, to be honest. Long `--` options should be used for descriptive names.

There is a possibility to hide options in `clap`, so I guess we could go with your other idea and just add a second option which could be hidden.

**Comment by selfup** [comment]
Yea hiding the `--c` so we can get a `-c` would be interesting. If I have time I'll see what can be done about an upstream to clap. Otherwise I will attempt to hide the long "fakename"

**Comment by selfup** [comment]
Ok updated my PR: https://github.com/sharkdp/hexyl/pull/48#issuecomment-460449756

**Comment by selfup** [comment]
Let me know if those PRs resolved the issue @FauxFaux :smile:
