### ISSUE TITLE
Is a Chocolatey package interesting?

### ISSUE THREAD

**Issue by ErichDonGubler** [sharkdp/hexyl#52]
I'd be more than happy to create an automatically updating Chocolatey package to hand off to whoever wants it -- is that interesting at all? I use Chocolatey to automate my own workflow right now, and this is a slick tool I'd love to add to my automatic toolbelt. :)

**Comment by sharkdp** [comment]
Absolutely - I'm always happy if there are people who are willing to create new packaging options. Once a package is available, we can add installation instructions to the README.

Please note, however, that I am personally not going to put time into maintenance of these packages, especially if it concerns a system that I am not using myself.

**Comment by sharkdp** [comment]
Closing this, as it doesn't make too much sense to track this here.
