### ISSUE TITLE
Squeeze zero rows

### ISSUE THREAD

**Issue by moshohayeb** [sharkdp/hexyl#53]
A useful feature hexdump is the ability to compress contigous rows of 0s with a *

dd if=/dev/zero of=swapfile bs=1024k count=1
mkswap swapfile
hexdump swapfile

0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0000400 0001 0000 00ff 0000 0000 0000 5dd8 a838
0000410 6fe7 d247 cc9b 6af5 a41d 50da 0000 0000
0000420 0000 0000 0000 0000 0000 0000 0000 0000
*
0000ff0 0000 0000 0000 5753 5041 5053 4341 3245
0001000 0000 0000 0000 0000 0000 0000 0000 0000
*
0100000

I was wondering if this is something hexyl can implement

**Comment by sharkdp** [comment]
Thank you for the feedback.

I will personally not have the time to implement this, but that sounds like a useful feature!

**Comment by sharkdp** [comment]
Implemented in #59 by @awidegreen.
