### ISSUE TITLE
cargo install failure

### ISSUE THREAD

**Issue by dvejmz** [sharkdp/hexyl#58]
Hi,

I'm trying to install hexyl via cargo but I am getting a couple of compilation errors.

```
error: expected one of `,` or `as`, found `::`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/hexyl-0.4.0/src/main.rs:8:28
  |
8 | use std::io::{self, prelude::*, StdoutLock};
  |                            ^^ expected one of `,` or `as` here

error: expected one of `;`, `as`, or `self`, found `::`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/hexyl-0.4.0/src/main.rs:8:28
  |
8 | use std::io::{self, prelude::*, StdoutLock};
  |                            ^^ expected one of `;`, `as`, or `self` here

error: aborting due to 2 previous errors

error: failed to compile `hexyl v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-install.yy1MBc6NxEZT`
```

Some details about my environment.

**OS**: Fedora 29 `Linux dev.localdomain 4.20.16-200.fc29.x86_64 #1 SMP Thu Mar 14 15:10:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
**Rust version**: `1.33.0`
**rustc version**: `rustc 1.23.0 (766bd11c8 2018-01-01)`
**cargo version**: `cargo 0.24.0 (45043115c 2017-12-05)`

Thanks

**Comment by bjorn3** [comment]
Updating rustc will probably fix this:

```
$ rustup update stable
```

**Comment by sharkdp** [comment]
Yes, the README states that you need Rust 1.30 or higher to compile from source.
