### ISSUE TITLE
Add link to official Debian/Ubuntu packages

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hexyl#77]
https://packages.debian.org/buster/hexyl
https://packages.ubuntu.com/eoan/hexyl

**Comment by selfup** [comment]
Would a checksum be something that could be added for these builds (or all builds in general)?

Otherwise, do these just need to be added to the README?

Thanks

**Comment by sharkdp** [comment]
Not sure why we would need any checksums. I just wanted to add a section in the README which links to the official packages, yes. Similar to what we did for `fd`: https://github.com/sharkdp/fd#installation
