### ISSUE TITLE
Print error message if parsing of --length/--skip/… fails

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/hexyl#97]
We should print an error if the parsing of the size argument for `--length`, `--skip`, … fails. Currently, we silently ignore the argument:
```
▶ echo 12345 | hexyl --skip 2b   
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000002│ 33 34 35 0a             ┊                         │345_    ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘

~                                                                                                       
▶ echo 12345 | hexyl --skip 2byte
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 31 32 33 34 35 0a       ┊                         │12345_  ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

I'd prefer if we use `anyhow` for error handling (if we want to rely on a library at all).

If we want to have good error messages, we probably want to modify
```
fn parse_byte_count(n: &str, block_size: PositiveI64) -> Option<PositiveI64>
```
to return a `Result<PositiveI64>` with several possible error paths.

**Comment by sharkdp** [comment]
this has actually already been brought up by @ErichDonGubler here: https://github.com/sharkdp/hexyl/issues/44#issuecomment-634105599

**Comment by ErichDonGubler** [comment]
If you want to assign this to me, I'm more than happy to take it. `anyhow` is an easy way to add some simple error handling, and this should be fast. :)

**Comment by sharkdp** [comment]
> If you want to assign this to me, I'm more than happy to take it

:+1:

**Comment by ErichDonGubler** [comment]
How's this issue looking? I believe we handled the missing error diagnostics for parse failures here.

**Comment by sharkdp** [comment]
Absolutely. Forgot to close it. Thanks!
